# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Test_power(object):
    def setupUi(self, Test_power):
        Test_power.setObjectName("Test_power")
        Test_power.resize(424, 247)
        self.gridLayout_2 = QtWidgets.QGridLayout(Test_power)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(Test_power)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.startvolt = QtWidgets.QLineEdit(Test_power)
        self.startvolt.setObjectName("startvolt")
        self.gridLayout.addWidget(self.startvolt, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(Test_power)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.open_csv = QtWidgets.QCommandLinkButton(Test_power)
        self.open_csv.setObjectName("open_csv")
        self.gridLayout.addWidget(self.open_csv, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Test_power)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Test_power)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.channl = QtWidgets.QLineEdit(Test_power)
        self.channl.setObjectName("channl")
        self.gridLayout.addWidget(self.channl, 0, 1, 1, 1)
        self.finvolt = QtWidgets.QLineEdit(Test_power)
        self.finvolt.setObjectName("finvolt")
        self.gridLayout.addWidget(self.finvolt, 2, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(Test_power)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 5, 1, 1, 1)
        self.step = QtWidgets.QLineEdit(Test_power)
        self.step.setObjectName("step")
        self.gridLayout.addWidget(self.step, 3, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tcpcheck = QtWidgets.QPushButton(Test_power)
        self.tcpcheck.setStyleSheet("background: rgb(255,0,0)")
        self.tcpcheck.setObjectName("tcpcheck")
        self.verticalLayout.addWidget(self.tcpcheck)
        self.startputten = QtWidgets.QPushButton(Test_power)
        self.startputten.setStyleSheet("")
        self.startputten.setObjectName("startputten")
        self.verticalLayout.addWidget(self.startputten)
        self.exitputten = QtWidgets.QPushButton(Test_power)
        self.exitputten.setIconSize(QtCore.QSize(16, 16))
        self.exitputten.setObjectName("exitputten")
        self.verticalLayout.addWidget(self.exitputten)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Test_power)
        QtCore.QMetaObject.connectSlotsByName(Test_power)
        Test_power.setTabOrder(self.channl, self.startvolt)
        Test_power.setTabOrder(self.startvolt, self.finvolt)
        Test_power.setTabOrder(self.finvolt, self.step)
        Test_power.setTabOrder(self.step, self.open_csv)
        Test_power.setTabOrder(self.open_csv, self.startputten)
        Test_power.setTabOrder(self.startputten, self.exitputten)

    def retranslateUi(self, Test_power):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowIcon(QtGui.QIcon('Logo.ico'))
        Test_power.setWindowTitle(_translate("Test_power", "Mega"))
        self.label_4.setText(_translate("Test_power", "    电压步进"))
        self.label.setText(_translate("Test_power", "    最小电压"))
        self.open_csv.setText(_translate("Test_power", "打开数据文件"))
        self.label_2.setText(_translate("Test_power", "        电路"))
        self.label_3.setText(_translate("Test_power", "    最大电压"))
        self.tcpcheck.setText(_translate("Test_power", "连接PG"))
        self.startputten.setText(_translate("Test_power", "开始"))
        self.exitputten.setText(_translate("Test_power", "退出"))
